server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp:localhost/~/sampledb
      username: sa
      password:

  h2:
    console:
      enabled: true
      path: /h2-console
